name             'kubernetes'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Resources for managing Kubernetes'
version          '2.0.1'
source_url       'https://github.com/chef-cookbooks/kubernetes'
issues_url       'https://github.com/chef-cookbooks/kubernetes/issues'
chef_version     '>= 15.3'

supports 'all'
